# Generated by Django 5.2.6 on 2025-09-23 23:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('leather', 'Leather'), ('synthetic', 'Synthetic'), ('fabric', 'Fabric'), ('rubber', 'Rubber'), ('foam', 'Foam'), ('metal', 'Metal'), ('plastic', 'Plastic')], max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('supplier', models.CharField(max_length=100)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(default='sq_ft', max_length=20)),
                ('minimum_order', models.IntegerField(default=1)),
                ('lead_time_days', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='FootwearCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.footwearcategory')),
            ],
            options={
                'verbose_name_plural': 'Footwear Categories',
            },
        ),
        migrations.CreateModel(
            name='FootwearProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids'), ('U', 'Unisex')], max_length=1)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heel_height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sole_thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('customizable', models.BooleanField(default=False)),
                ('production_time_days', models.IntegerField(default=14)),
                ('minimum_order_quantity', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.footwearcategory')),
                ('available_materials', models.ManyToManyField(to='products.material')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=100)),
                ('custom_colors', models.JSONField(default=dict)),
                ('special_instructions', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customization_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.footwearproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DesignMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=50)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customdesign')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.material')),
            ],
            options={
                'unique_together': {('design', 'component')},
            },
        ),
        migrations.AddField(
            model_name='customdesign',
            name='selected_materials',
            field=models.ManyToManyField(through='products.DesignMaterial', to='products.material'),
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('size_breakdown', models.JSONField(default=dict)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion', models.DateField()),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_production', 'In Production'), ('quality_check', 'Quality Check'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('custom_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.customdesign')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.footwearproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('US', 'United States'), ('EU', 'European Union'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('CN', 'China')], max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids'), ('U', 'Unisex')], max_length=1)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('region', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='SizeConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_value', models.CharField(max_length=10)),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('size_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sizechart')),
            ],
            options={
                'unique_together': {('size_chart', 'size_value')},
            },
        ),
        migrations.AddField(
            model_name='footwearproduct',
            name='available_sizes',
            field=models.ManyToManyField(to='products.sizeconversion'),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sizeconversion'),
        ),
        migrations.CreateModel(
            name='WholesaleCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_tier', models.CharField(choices=[('bronze', 'Bronze (5%)'), ('silver', 'Silver (10%)'), ('gold', 'Gold (15%)'), ('platinum', 'Platinum (20%)')], default='bronze', max_length=20)),
                ('payment_terms', models.IntegerField(default=30)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=8)),
                ('component_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='products.footwearproduct')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.material')),
            ],
            options={
                'unique_together': {('product', 'material', 'component_name')},
            },
        ),
    ]
